# Permalinks
permalink:           p/:title

collections:
  articles:
    output: true
  definitions:
    output: true

# Setup
title:               Artificial Trust
tagline:             On thinking
url:                 https://zelaza.pair.com/straz/org/at





