title: Artificial Trust
tagline: On thinking
url: "https://artificialtrust.com"

# Build settings
markdown: kramdown
theme: null
highlighter: rouge
secure: true
password: norbert
show_draft: false

# Markdown options
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Directories
source: .
destination: ./_site
includes_dir: _includes
layouts_dir: _layouts


collections:
  articles:
    output: true
  definitions:
    output: true
  diseases:
    output: true

# Sass handled externally (Dart Sass), so disable Jekyll’s Sass processing
sass:
  style: compressed
  load_paths:
    - assets/scss

# Plugins (all safe for GitHub Actions)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files from the build
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - README.md
  - .github
  - assets/scss # SCSS compiled separately by Dart Sass
  - _definitions/MDX

# Permalinks
permalink: p/:title

