# Permalinks
permalink:           p/:title

collections:
  articles:
    output: true
  definitions:
    output: true

# Setup
title:               Artificial Trust
tagline:             On thinking
url:                 https://strassmann.org/at/




