# Permalinks
permalink:           p/:title

collections:
  articles:
    output: true
  definitions:
    output: true
  diseases:
    output: true

sass:
  sass_dir: _sass
  style: compressed # Optional: keeps your production file small

# Setup
title: Artificial Trust
tagline: On thinking
url:     https://artificialtrust.com
secure: true
password: norbert
show_draft: false
exclude:
  - "*.mdx"
plugins:
  - jekyll-feed
